baseURL = "https://audax.tools/"
languageCode = "en-us"
title = "Audax Toolset"

theme = "terminal"

publishDir = "docs"

[markup.goldmark.renderer]
  unsafe = true
 
[params]
	contentTypeName = "docs"
	
[params.Logo]
	logoText = "Audax Toolset"