baseURL = "http://example.org/"
languageCode = "en-us"
title = "Audax Toolset"

theme = "terminal"

[markup.goldmark.renderer]
  unsafe = true
 
[params]
	contentTypeName = "docs"
	
[params.Logo]
	logoText = "Audax Toolset"