baseURL = "https://dynamobrowse.app/"
languageCode = "en-us"
title = "Dynamo-Browse"

theme = "terminal"

publishDir = "docs"

[markup.goldmark.renderer]
  unsafe = true
 
[params]
	themeColor = "blue"
	contentTypeName = "docs"
	centerTheme = true
	
[params.Logo]
	logoText = "Dynamo-Browse"

[menu]
[[menu.main]]
	identifier = "download"
	name = "Download"
	url = "/download"
	weight = 20
[[menu.main]]
	identifier = "docs"
	name = "Documentation"
	url = "/docs"
	weight = 40
[[menu.main]]
	identifier = "updates"
	name = "Updates"
	url = "/updates"
	weight = 50