baseURL = "https://dynamobrowse.app/"
languageCode = "en-us"
title = "Dynamo-Browse"

theme = "hugo-book"

publishDir = "docs"

[markup.goldmark.renderer]
  unsafe = true
 
[params]	
	BookTheme = "auto"
	BookMenuBundle = "/menu"
	
[params.Logo]
	logoText = "Dynamo-Browse"

[menu]
[[menu.main]]
	identifier = "download"
	name = "Download"
	url = "/download"
	weight = 20
[[menu.main]]
	identifier = "docs"
	name = "Documentation"
	url = "/docs"
	weight = 40
[[menu.main]]
	identifier = "updates"
	name = "Updates"
	url = "/updates"
	weight = 50